## PyTorch

#### PyTorch's forward and backward propagation

In [1]:
import torch 
print('GPU available:', torch.cuda.is_available())

# Forward pass
x = torch.tensor(2.0, requires_grad=True) # requires_grad=True allows tracking of operations on this tensor
y = x ** 2 
z = torch.sin(y)
print(f"Output z: {z.item()}") 

# Backward pass
z.backward() # dz/dx=dz/du*du/dx
print(f"Gradient of z with respect to x: {x.grad.item()}") # Gradient. 2*x*cos(x^2)

GPU available: True
Output z: -0.756802499294281
Gradient of z with respect to x: -2.614574432373047


#### Tensorflow's forward propagation

In [ ]:
import tensorflow as tf

input_shape = (2, 3)
x1 = tf.random.normal(input_shape, mean=0.0, stddev=1.0) # Normal distribution
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])

print(x1)
print(x2)
print(y.shape)
print(y)


tf.Tensor(
[[-0.7231767  -2.0968945  -1.5443535 ]
 [-0.9449558  -1.4036713  -0.81382334]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.02215126 -0.9703884  -2.9087512 ]
 [-0.4785774   0.75950986  0.7895814 ]], shape=(2, 3), dtype=float32)
(2, 3)
tf.Tensor(
[[-0.7010255  -3.067283   -4.453105  ]
 [-1.4235332  -0.6441614  -0.02424192]], shape=(2, 3), dtype=float32)


#### Keras's forward propagation

In [6]:
model = tf.keras.Sequential()
rs = tf.keras.layers.Reshape((3, 4), input_shape=(12,))
model.add(rs)
s = model.output_shape  # (None, 3, 4). # (mini batch size, 3, 4)
print(s)
model.add(tf.keras.layers.Reshape((-1, 2, 2)))   # (None, 3, 2, 2)
s = model.output_shape  # (None, 3, 4)
print(s)

(None, 3, 4)
(None, 3, 2, 2)


c:\Users\MAC\.conda\envs\venv_lmm\Lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
