## Tensor calculation

### Example for image tensor

In [2]:
import torch # PyTorch 라이브러리 가져오기

# 28x28 크기의 흑백 이미지 1장을 가정 (배치 크기 1)
image = torch.randn(1, 28, 28)
print("Original shape:", image.shape)  # 출력: Original shape: torch.Size()

# 이미지를 1차원 벡터로 펼치기 (Flattening)
# 28 * 28 = 784
flattened_image = image.view(1, 784)
print("Flattened shape:", flattened_image.shape)  # 출력: Flattened shape: torch.Size()

# -1을 사용하면 해당 차원의 크기를 자동으로 계산해준다.
flattened_image_auto = image.view(1, -1)
print("Flattened shape (auto):", flattened_image_auto.shape) # 출력: Flattened shape (auto): torch.Size()



Original shape: torch.Size([1, 28, 28])
Flattened shape: torch.Size([1, 784])
Flattened shape (auto): torch.Size([1, 784])


### Tensor operator
#### Add

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 덧셈
print(a + b)  # 출력: tensor([5, 7, 9])

# 곱셈
print(a * b)  # 출력: tensor([4, 10, 18])

tensor([5, 7, 9])
tensor([ 4, 10, 18])


Multiply

In [ ]:
input_features = torch.randn(1, 3)  # (1, 3) shape의 입력 데이터 (배치 크기 1, 특징 3개)
weights = torch.randn(3, 1)         # (3, 1) shape의 가중치 행렬 (특징 3개를 받아 1개의 출력 생성)

# 행렬 곱셈
output = torch.matmul(input_features, weights)
# 또는 output = input_features @ weights

print("Input shape:", input_features.shape)
print("Weights shape:", weights.shape)
print("Output shape:", output.shape)


Input shape: torch.Size([1, 3])
Weights shape: torch.Size([3, 1])
Output shape: torch.Size([1, 1])


#### Dot product

In [6]:
# Dot product 예제
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

dot_product = torch.dot(a, b)
print(f"dot product: {dot_product}")  # 1*4 + 2*5 + 3*6 = 32

dot product: 32.0


#### Tensor reshape, view, unsqueeze, squeeze

In [ ]:
import torch # PyTorch 라이브러리 가져오기

print('reshape')
x = torch.arange(24).reshape(2, 3, 4) # [2, 3, 4] 
print('reshape=', x.shape)
y = x.unsqueeze(0) # [1, 2, 3, 4]
print('unsqueeze=', y.shape)
print(y)
y = y.squeeze(0) # [2, 3, 4]
print('squeeze=', y.shape)
print(y)

reshape
reshape= torch.Size([2, 3, 4])
unsqueeze= torch.Size([1, 2, 3, 4])
tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])
squeeze= torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


#### Tensor transpose, permute, arange

In [7]:
x = torch.arange(0, 5)  # [0, 1, 2, 3, 4]
print('arange=', x)

x = x.reshape(1, 5)   # [1, 5].
print('reshape=', x.shape)
print(x)

y = x.transpose(0, 1)  # [5, 1].
print('transpose=', y.shape)
print(y)

z = x.permute(1, 0)  # [5, 1]. 
print('permute=', z.shape)
print(z)


arange= tensor([0, 1, 2, 3, 4])
reshape= torch.Size([1, 5])
tensor([[0, 1, 2, 3, 4]])
transpose= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
permute= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
